### ISSUE TITLE
Share and download maticas not work after switching between servers behind velocity

### ISSUE THREAD

**Issue by YehowahLiu** [End-Tech/syncmatica#31]
When using this mod in server which is behind velocity 's proxy, it only works correctly at the case that you connect to the target sub-server directly without using the command `/server abc`.
Even that you should never change your server which will make this mod not work again.

**Comment by nnnik** [comment]
Hello I do not know the proxies that you speak of.
Syncmatica has a statefil communication which needs to happen in a precise order.
Deviating from this order in ways which I did not foresee may cause unintended side effects.
Generally though I need more information about the other mod to devide how to handle this case.
That being said though I will not be able to handle this case as I won't have any internet until the 8th of december. (Apparently Germany is not a country that has reached the digital age yet)

**Comment by YehowahLiu** [comment]
[here](https://velocitypowered.com/) shows what is the proxy we use

**Comment by nnnik** [comment]
My assumption is that the proxy you use performs the full server-client handshake with your client.
Your client then assumes it is authorized.
When switching the server using a proxy, the client only sees thar the dimension changed while the new server sees an unauthorized client.
The solution possibly is to enable a new message type in the client/server that allows the client to check if it is still authorized and reauthorize if necessary.
That way each server would have its own syncmatics.

But this is what I think happens before checking the source.
What happens if you reconnect after you switched servers - is the last selected server still active and does syncmatica work if you are still connected?

**Comment by YehowahLiu** [comment]
Yes, reconnect after switch server will make it work again, and that's exactly the method we use now.

**Comment by YehowahLiu** [comment]
> My assumption is that the proxy you use performs the full server-client handshake with your client. Your client then assumes it is authorized. When switching the server using a proxy, the client only sees thar the dimension changed while the new server sees an unauthorized client. The solution possibly is to enable a new message type in the client/server that allows the client to check if it is still authorized and reauthorize if necessary. That way each server would have its own syncmatics.
Got the point, reasonable assumption

**Comment by nnnik** [comment]
I just realized that the solution is way easier.
The server initializes communication by sending a message.
As such the client receives that message but doesn't handle it because it is unexpected.
I just need to properly implement the handling for the case when the client receives a hello but thinks it is verified on the server.
Im also picking up developing this mod again despite my lack of internet since Im less busy now and will have it in about a week or 2.
This fix might be part of the next release but no promises

**Comment by nnnik** [comment]
Hey this might work with this update.

**Comment by YehowahLiu** [comment]
It works!

**Comment by nnnik** [comment]
pog
